name: jade
channels:
  - defaults
dependencies:
  - python=3.7
  - pip>=19.1
  - pip:
    - click
    - feather-format
    - ipython
    - jupyter
    - matplotlib>=3.0.3
    - opendssdirect.py>=0.3.7
    - pandas
    - prettytable
    - psutil>=5.6.2
    - pyyaml
    - statsmodels>=0.10.1
    - toml>=0.10.0
