package:
    name: nrel-jade
    version: {{ environ.get('GIT_DESCRIBE_TAG','').replace('v', '', 1) }}

source:
    git_url: ../

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - pip
    - setuptools
    - click
    - filelock
    - numpy
    - pandas
    - plotly
    - prettytable
    - psutil
    - pydantic
    - toml>=0.10.0
  run:
    - python
    - pip
    - click
    - filelock
    - {{ pin_compatible('numpy') }}
    - pandas
    - plotly
    - prettytable
    - psutil
    - pydantic
    - toml>=0.10.0

about:
  home: "https://github.com/NREL/jade"
  license: BSD 3-Clause
  summary: "Provides HPC workflow automation services"
  doc_url: "https://nrel.github.io/jade"
  dev_url: "https://github.com/NREL/jade"
